[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@aave/protocol-v2/=lib/protocol-v2/",
    "@compound/=lib/compound=protocol/",
    "@aave/core-v3/=lib/aave-v3-core",
    "foundry-devops/=lib/foundry-devops/",   
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
